### ISSUE TITLE
Wish: Support for deserializing JSON containing multiple items

### ISSUE THREAD

**Issue by andydandy74** [radumg/DynaWeb#28]
## Expected Behavior

Hey Radu, my webservice returns multiple items for some requests, e.g.:
```
{
   "property1":"ABC",
   "property2":"DEF"
},
{
   "property1":"GHI",
   "property2":"JKL"
}
```
What I would like to see the ```Helpers.Deserialize``` nodes return is something like this:
![grafik](https://user-images.githubusercontent.com/3014437/48801699-54ed5d80-ed0d-11e8-9ae7-df0b42b3c766.png)

## Actual Behavior
Currently, the ```Helpers.Deserialize``` nodes cannot deal with that and throw this warning:
```
Additional text encountered after finished reading JSON content: ,. Path '', line 4, position 1.
````

## Steps to Reproduce the Problem
- Copy sample JSON from above
- Paste into ```String Input``` node
- Connect to ```Helpers.DeserializeAsDictionary```
- Run
![grafik](https://user-images.githubusercontent.com/3014437/48801737-6b93b480-ed0d-11e8-8161-df64dba2a42e.png)

## Specifications

    - Dynamo : 1.3.3
    - Operating system : Windows 10
    - .NET :  4.7.2

**Comment by radumg** [comment]
Since you’re returning an array of 2 objects, your JSON should start with [ and end with ]. Alternative would be to start/end with {/} if the 2 objects were properties of one json object, otherwise the JSON isn’t valid.

Typed on a tiny screen

**Comment by andydandy74** [comment]
I already tried turning it into a proper JSON array. That gave me an error as well. I'll re-check tomorrow if it was the same error message.

**Comment by andydandy74** [comment]
Just checked: passing a JSON array also returns an error:
```
Error reading JObject from JsonReader. 
Current JsonReader item is not an object: 
StartArray. Path '', line 1, position 1.
```

**Comment by radumg** [comment]
Thanks Andreas, let me look at it and troubleshoot what’s going on. 

Typed on a tiny screen

**Comment by radumg** [comment]
hey @andydandy74 , had a look at it and here's what I found : 

- at first, i had an issue with the string node outputting `null`, it seems it doesn't like the curly braces sometimes, so make sure it outputs something with a `watch` node

DynaWeb can parse a single item just fine
![single item](https://user-images.githubusercontent.com/11439624/48894732-5cab2000-ee3b-11e8-898d-d90fc55a7c9b.png)

Then, as suspected, the JSON you posted is not a valid so it will fail to deserialise.
![bad json](https://user-images.githubusercontent.com/11439624/48894750-66348800-ee3b-11e8-8b50-dddc88152fdb.png)

However, if you wrap it in a JSON array with `[` and `]` it should now work with the `Helpers.Deserialise` node. This one works because it recursively parses things whereas the other nodes expect a single JSON object as input.
![recursive](https://user-images.githubusercontent.com/11439624/48894976-e6f38400-ee3b-11e8-9a9a-df13690fe9e7.png)

One last thing you can do is wrap your 2 JSON objects inside a root object and name them as per below . The `Helpers.Deserialise` node will again work and the `Helpers.DeserialiseAsDictionary` will partially work - it's not recursive so it will only handle the top-level elements, you'll need to deserialise its children again with this one.
![json objects](https://user-images.githubusercontent.com/11439624/48895015-fa9eea80-ee3b-11e8-9d55-76cb8509dbb9.png)

**Comment by radumg** [comment]
Hopefully this helps you out - I really recommend using the `Helpers.Deserialise` node as it's recursive and in `Dynamo 2.0` outputs native Dynamo dictionaries as seen in screenshots above (might do in Dynamo 1.x too, been a while since i tested it there.)

**Comment by andydandy74** [comment]
Thanks for looking into it, Radu. Unfortunately, I do not have control over the output of the webservice in question. Since I need the property names, I need to use the DeserializeAsDictionary node as that is the only one that'll return them in 1.3 :-)
As a workaround, I've decided to convert the malformed JSON into a JSON array and then split that array into multiple JSON objects with a custom node.
![grafik](https://user-images.githubusercontent.com/3014437/48908020-73686b80-ee69-11e8-94c4-6a5f470b4a41.png)
Also, thanks for pointing out that the Deserialize node is recursive. That'll be very useful when switching to 2.x

**Comment by radumg** [comment]
That's a good workaround, glad it works!

Out of curiosity, what happens when you plug in the output of `Helpers.SplitJSONArray` into `Helpers.Deserialise` on `Dynamo 1.3` ? That node outputs a native .NET dictionary and I think that used to be handled by Dynamo in `1.3` too.

**Comment by andydandy74** [comment]
In 1.3 it only outputs the values, not the keys/properties, so that wasn't an option.
