### ISSUE TITLE
Nodes used in samples reference assembly from missing location

### ISSUE THREAD

**Issue by 3sk0r** [radumg/DynaWeb#9]
## Expected Behavior

Expected Node to be resolved (available)

## Actual Behavior
Node's path points to a non existing location (C:\Users\*username*\AppData\Roaming\Dynamo\Dynamo Core\Desktop\testing\DynWWW.dll)
![image](https://user-images.githubusercontent.com/15014799/29770932-3760571c-8be9-11e7-83fc-62f421de41db.png)

## Steps to Reproduce the Problem

  1. Open DynaWeb.dyn sample
  2. 
  3.

## Specifications

    - Dynamo : (ex : 1.3.1)
    - Operating system : Windows 10
    - .NET : 4.6

**Comment by radumg** [comment]
Thanks @3sk0r for reporting. Can you try adding that node directly from the library and replacing it in the graph ?

FYI That path is where I was staging the DLL on my PC and this happens sometimes with Zero-Touch nodes stubbornly clinging on to their former location instead of using the package path.

**Comment by 3sk0r** [comment]
Yes, that's what I tried and the node is fine when I select it directly from the library. Replaced node and saved the file.

**Comment by radumg** [comment]
Thanks @3sk0r , will update samples to point to package folder, or remove the assembly references altogether.
![assembly reference](https://user-images.githubusercontent.com/11439624/29773095-c2518f1c-8bf3-11e7-8810-18a1aed21a60.PNG)
